# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='desc',
        ),
    ]
