# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('course_a', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='user_favorite',
            field=models.ManyToManyField(related_name='favorite', to='login.User'),
        ),
    ]
