# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_a', '0002_course_user_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user_favorite',
            new_name='favorites',
        ),
    ]
