# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_a', '0003_auto_20180122_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='favorites',
            new_name='user_favorites',
        ),
    ]
